# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

alert: !include alerts.yaml
automation: !include automations.yaml
automation blackouts: !include automations_blackout.yaml
automation climats: !include automations_climat.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Видалено ці записи, їх потрібно перенести в secrets.yaml
# password: !secret my_password
# token: !secret my_token

python_script:

climate:
  - platform: smartir
    name: Кондіціонер у вітальні
    unique_id: livingroom_ac
    device_code: !secret climate_device_code
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.broadlink_rc4c_mini
      delay_secs: 0.5
      num_repeats: 2
    temperature_sensor: sensor.termometr_temperature
    humidity_sensor: sensor.termometr_humidity
    power_sensor: switch.smart_plug_socket_1

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

sensor:
  - platform: history_stats
    name: "Отримані дані за сьогодні (Gb)"
    entity_id: sensor.miwifi_router_data_received
    state: 'Gb'
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: "Відвантажені дані за сьогодні (Gb)"
    entity_id: sensor.miwifi_router_data_sent
    state: 'Gb'
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: template
    sensors:
      ac_in_power:
        friendly_name: "AC потужність зарядки"
        unit_of_measurement: 'W'
        device_class: power
        value_template: "{{ states('sensor.delta_2_ac_in_power') | float(0) }}"
      
      ac_out_power:
        friendly_name: "AC потужність на виході"
        unit_of_measurement: 'W'
        device_class: power
        value_template: "{{ states('sensor.delta_2_ac_out_power') | float(0) }}"

      battery_level:
        friendly_name: "Рівень заряду батареї"
        unit_of_measurement: '%'
        device_class: battery
        value_template: "{{ states('sensor.delta_2_battery_level') | float(0) }}"

      solar_in_power:
        friendly_name: "Сонячна енергія (вхід)"
        unit_of_measurement: 'W'
        device_class: power
        value_template: "{{ states('sensor.delta_2_solar_in_power') | float(0) }}"
