# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

alert: !include alerts.yaml
automation: !include automations.yaml
automation blackouts: !include automations_blackout.yaml
automation climats: !include automations_climat.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml


python_script:

climate:
  - platform: smartir
    name: Кондіціонер у вітальні
    unique_id: livingroom_ac
    device_code: !secret climate_device_code
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.broadlink_rc4c_mini
      delay_secs: 0.5
      num_repeats: 2
    temperature_sensor: sensor.termometr_temperature
    humidity_sensor: sensor.termometr_humidity
    power_sensor: switch.smart_plug_socket_1

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

input_boolean:
  reset_statistics:
    name: Reset Statistics
    initial: off
    icon: mdi:refresh